<?php declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;
use Siteation\StoreInfoPaymentLogos\ViewModel\StoreInfoPaymentLogos;

/** @var ViewModelRegistry $viewModels */
/** @var Template $block */
/** @var Escaper $escaper */

/** @var StoreInfoPaymentLogos $storeInfoPaymentLogos */
$storeInfoPaymentLogos = $viewModels->require(StoreInfoPaymentLogos::class);
$paymentOptions = $storeInfoPaymentLogos->getPaymentMethods();

if (!$paymentOptions) {
    return '';
}
?>

<ul class="flex flex-wrap gap-4">
    <?php foreach ($paymentOptions as $option): ?>
        <li class="icon-<?= $escaper->escapeHtml($option) ?>">
            <svg xmlns="http://www.w3.org/2000/svg" width="48" height="32">
                <title><?= $escaper->escapeHtml(__('Go to our %1 page', 'Facebook')); ?></title>
                <use href="<?= $block->getViewFileUrl('Siteation_StoreInfoPaymentLogos::images/payments.svg'); ?>#<?= $escaper->escapeHtml($option) ?>" />
            </svg>
        </li>
    <?php endforeach; ?>
</ul>
