<?php declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;
use Siteation\StorePaymentLogos\ViewModel\StorePaymentLogos;

/** @var ViewModelRegistry $viewModels */
/** @var Template $block */
/** @var Escaper $escaper */

/** @var StorePaymentLogos $storePaymentLogos */
$storePaymentLogos = $viewModels->require(StorePaymentLogos::class);
$paymentOptions = $storePaymentLogos->getPaymentMethods();
$paymentIconPath = 'Siteation_StorePaymentLogos::images/payment-logos.svg';

if (!$paymentOptions) {
    return '';
}
?>

<ul class="flex flex-wrap gap-4">
    <?php foreach ($paymentOptions as $option): ?>
        <?php if ($option === "creditcard"): ?>
            <li class="icon-maestro">
                <svg xmlns="http://www.w3.org/2000/svg" width="48" height="32">
                    <title>maestro</title>
                    <use href="<?= $block->getViewFileUrl($paymentIconPath); ?>#maestro" />
                </svg>
            </li>
            <li class="icon-visa">
                <svg xmlns="http://www.w3.org/2000/svg" width="48" height="32">
                    <title>visa</title>
                    <use href="<?= $block->getViewFileUrl($paymentIconPath); ?>#visa" />
                </svg>
            </li>
            <?php continue; ?>
        <?php endif; ?>
        <li class="icon-<?= $escaper->escapeHtml($option) ?>">
            <svg xmlns="http://www.w3.org/2000/svg" width="48" height="32">
                <title><?= $escaper->escapeHtml($option) ?></title>
                <use href="<?= $block->getViewFileUrl($paymentIconPath); ?>#<?= $escaper->escapeHtml($option) ?>" />
            </svg>
        </li>
    <?php endforeach; ?>
</ul>
