<?php declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;
use Siteation\HyvaIconsPayment\ViewModel\PaymentIcons;
use Siteation\StoreInfoPayments\ViewModel\StorePayments;

/** @var ViewModelRegistry $viewModels */
/** @var Template $block */
/** @var Escaper $escaper */

/**
 * To use a diffent style, update the viewmodal,
 * to for example `Siteation\HyvaIconsPayment\ViewModel\PaymentIcons`
 *
 * @var PaymentIcons $paymentIcons
 */
$paymentIcons = $viewModels->require(PaymentIcons::class);

/** @var StorePayments $storePayments */
$storePayments = $viewModels->require(StorePayments::class);

$paymentOptions = $storePayments->getPaymentMethods();

if (!$paymentOptions) {
    return '';
}
?>

<ul
    role="list"
    class="payment-logos px-4 py-6 bg-gray-100 flex flex-wrap justify-center gap-4"
    aria-label="<?= $escaper->escapeHtmlAttr(__('Payment Methods')) ?>"
>
    <?php foreach ($paymentOptions as $option): ?>
        <li>
            <?= $paymentIcons->renderHtml($option, '', 48, 32, ["title" => __('Logo %1', $option)]); ?>
        </li>
    <?php endforeach; ?>
</ul>
