<?php declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;
use Siteation\HyvaIconsPayment\ViewModel\PaymentIcons;
use Siteation\StoreInfoPayments\ViewModel\StorePayments;

/** @var ViewModelRegistry $viewModels */
/** @var Template $block */
/** @var Escaper $escaper */

/**
 * To use a diffent style, update the viewmodal,
 * to for example `Siteation\HyvaIconsPayment\ViewModel\PaymentIcons`
 *
 * @var PaymentIcons $paymentIcons
 */
$paymentIcons = $viewModels->require(PaymentIcons::class);

/** @var StorePayments $storePayments */
$storePayments = $viewModels->require(StorePayments::class);

$paymentOptions = $storePayments->getPaymentMethods();

if (!$paymentOptions) {
    return '';
}

$classList = $block->getClassList() !== null ? $block->getClassList() : 'self-start flex flex-wrap gap-4 pr-4 w-full lg:w-3/4';
?>

<ul
    role="list"
    class="payment-logos <?= $escaper->escapeHtmlAttr($classList) ?>"
    aria-label="<?= $escaper->escapeHtmlAttr(__('Payment Methods')) ?>"
>
    <?php foreach ($paymentOptions as $option): ?>
        <li>
            <?= $paymentIcons->renderHtml($option, '', 64, 48, ["title" => __('Logo %1', $option)]); ?>
        </li>
    <?php endforeach; ?>
</ul>
