<?php declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;
use Siteation\HyvaIconsPayment\ViewModel\PaymentIcons;
use Siteation\StoreInfoPayments\ViewModel\StorePayments;

/** @var ViewModelRegistry $viewModels */
/** @var Template $block */
/** @var Escaper $escaper */

/** @var PaymentIcons $paymentIcons */
$paymentIcons = $viewModels->require(PaymentIcons::class);

/** @var StorePayments $storePayments */
$storePayments = $viewModels->require(StorePayments::class);

$paymentOptions = $storePayments->getPaymentMethods();

if (!$paymentOptions) {
    return '';
}
?>

<ul class="payment-logos flex flex-wrap gap-4">
    <?php foreach ($paymentOptions as $option): ?>
        <li>
            <?= $paymentIcons->renderHtml($option, '', 64, 48); ?>
        </li>
    <?php endforeach; ?>
</ul>
